=== franek73/HTML-XML-Project/HIH - Projekt XML/DTD.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT hipertext (about, history, types)>

<!ENTITY % source "source CDATA #REQUIRED">
<!ENTITY % number "number CDATA #IMPLIED">

<!ELEMENT about (description, extrainformation)>
<!ELEMENT description (#PCDATA)>
<!ATTLIST description length (short|long) #IMPLIED>
<!ELEMENT extrainformation (link | image)>
<!ATTLIST extrainformation kind CDATA #IMPLIED>
<!ELEMENT link (#PCDATA)>
<!ATTLIST link %source;>

<!ELEMENT history (description, extrainformation, constructor)>

<!ELEMENT constructor (name, surname, birth, death, description, life)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT birth (#PCDATA)>
<!ELEMENT death (#PCDATA)>
<!ELEMENT life (#PCDATA)>

<!ELEMENT types (typeslist, type+)>
<!ELEMENT typeslist (#PCDATA)>

<!ELEMENT type (name, description, images, link*)>
<!ATTLIST type %number;>
<!ELEMENT images (image+)>
<!ELEMENT image (#PCDATA)>
<!ATTLIST images howmany CDATA #IMPLIED>
<!ATTLIST image size CDATA "x1">
<!ATTLIST image %source;>
<!ATTLIST image %number;>

=== franek73/HTML-XML-Project/HIH - Projekt XML/XMLdoDTD.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE hipertext SYSTEM "DTD.dtd">

<hipertext>
	
	<about>
		<description length="long">
			Saksofon (wł. sassofono, skrót: sass.; ang. saxophone, sax.) – instrument dęty drewniany z grupy
			aerofonów stroikowych. Mimo metalowego korpusu, zaliczany jest do drewnianych, ponieważ posiada drewniany
			stroik tak jak klarnet i dźwięk można uzyskać poprzez czarę tak samo jak w klarnecie. Występuje w dziewięciu
			odmianach, różniących się wielkością i zakresem dźwięków. Od najmniejszych saksofonów – soprillo, po
			największe – subkontrabasowe, najczęściej budowane w strojach B i Es (mniej typowe: C i F).

			Saksofon skonstruowany został przez Adolpha Saxa w pierwszej połowie XIX wieku. Od początku XX wieku wiele
			zapisów nut na saksofon powstało na zlecenie zamożnej, początkującej saksofonistki – Elizy Hall. Współpracowała
			ona z kompozytorami takimi, jak: Claude Debussy, Gabriel Fauré, Vincent d’Indy i André Caplet. Muzyka na ten
			instrument jest wzbogacona twórczością jego promotorów, np. niemieckiego saksofonisty Sigurda Raschèra czy
			francuskiego muzyka Marcela Mule.
		</description>
		<extrainformation kind="links">
			<link source="https://muzaisprzet.com/nauka-gry-na-saksofonie/">Jak zacząć przygodę z saksofonem?</link>
		</extrainformation>
	</about>
	<history>
		<description length="long">
			Historia saksofonu rozpoczęła się najprawdopodobniej w roku 1841, kiedy to przygotowany na wystawę instrumentów
			w Brukseli pakunek ktoś kopnął w niewyjaśnionych okolicznościach. Pogięty i zniszczony instrument nie nadawał
			się do prezentacji. Sądząc z opisów, pakunek zawierał nowy, skonstruowany niedawno instrument – saksofon.

			Pierwsza wzmianka o saksofonie, autorstwa Hektora Berlioza, ukazała się 12 czerwca 1842 roku w paryskim Journal
			des Debats i ta data została przyjęta za metrykę powstania saksofonu, chociaż instrument miał swoją publiczną
			premierę 3 lutego 1844 r., a opatentowany został dopiero 28 czerwca roku 1846. Saksofon (Le Saxophon), nazywany
			po jego wynalazcy, był instrumentem z grupy dętych drewnianych. Miał dziewiętnaście klap, co uczyniło go
			podobnym do instrumentu ophicleide.

			Ustnik, w przeciwieństwie do ustników instrumentów dętych blaszanych, był podobny do ustnika klarnetu basowego.
			Co ciekawe, pierwszym opisywanym saksofonem był saksofon basowy w stroju C; dopiero później, z konieczności
			nadania większej ruchliwości, Adolf Sax skonstruował baryton, alt, tenor i sopran – mniejsze odmiany saksofonu.
			Skala pierwszego saksofonu była o siedem dźwięków większa niż późniejsze modele, które Sax przebudował ze
			względu na gorsze możliwości brzmieniowe najwyższych dźwięków prototypu.

			Wiosną 1843 roku rozpoczął produkcję instrumentów blaszanych z nowym mechanizmem obrotowym, zamiast tłokowym. W
			listopadzie 1843 roku, podczas wystawienia opery Don Sebastian Donizettiego, muzycy odmówili wykonania partii
			klarnetu basowego na instrumencie zrobionym przez Saxa. Sax zadeklarował, że wykona ją osobiście, ale muzycy
			zagrozili strajkiem. Sax wspólnie z Donizettim musieli ustąpić.

			Wkrótce po premierze pierwszego saksofonu Adolf Sax zademonstrował swoje instrumenty w Konserwatorium Paryskim,
			gdzie słuchali go znani wówczas muzycy i kompozytorzy: Auber (sławny wówczas kompozytor La Muette de Portici –
			opery wykonywanej w Brukseli 21 września 1830, będącej sygnałem dla Rewolucji Belgijskiej), Halévy, Habeneck,
			Monnais i inni, którzy chwalili Saxa za nowatorstwo i muzykalność. Po sukcesie prezentacji Sax otworzył warsztat
			w Paryżu przy ulicy Saint Georges 10, gdzie zabrał się energicznie do pracy, nader często jednak popadając w
			konflikty z zatrudnianymi rzemieślnikami. Na siedemnastego i dwudziestego pierwszego czerwca przypadają daty
			pierwszych francuskich patentów saksofonowych.

			Na początku 1844 roku warsztat Saxa odwiedził Rossi, który urzeczony brzmieniem saksofonu sprowadził go do
			Konserwatorium w Bolonii. Najwierniejszym zwolennikiem saksofonu i talentu Saxa był jednak Hektor Berlioz –
			gorący propagator nowego instrumentu, konsekwentnie wszędzie tam, gdzie koncertował.

			Latem 1844 saksofon został pokazany na Paris Industrial Exhibision i prezentowany wobec Króla Louisa Phollippe i
			Królowej Marie Amelie.

			Od roku 1844 warsztat Saxa odwiedzała śmietanka życia muzycznego, literackiego i społecznego Paryża. Przy każdej
			okazji Sax demonstrował możliwości swoich instrumentów, podczas improwizowanych koncertów. W tym samym roku Sax
			otworzył filię fabryki w Anglii, a wkrótce po tym jego młodszy brat Henry wyemigrował do Ameryki, gdzie założył
			manufakturę instrumentów dętych w Filadelfii. Latem 1844 saksofon został pokazany na Paris Industrial Exhibision
			i prezentowany wobec Króla Louisa Phollippe i Królowej Marie Amelie.

			Rok 1845 okazał się przełomowy w życiu Adolfa Saxa. Dopiero teraz zaczęła przełamywać się stopniowa niechęć
			muzyków i ś rodowiska konstruktorów instrumentów. Chociaż nadal miał wielu wrogów, stopniowo pokonywał
			zniechęcenie do swojej osoby. Budził olbrzymie kontrowersje, nazywając grupę saxhornów swoim nazwiskiem
			(protestowali niemieccy konstruktorzy: Stolzel i Blumel). W tym samym roku Sax otworzył filię fabryki w Anglii,
			a wkrótce po tym jego młodszy brat Henry wyemigrował do Ameryki, gdzie w Filadelfii założył manufakturę
			instrumentów dętych.

			W 1858 roku Sax został kierownikiem klasy saksofonu przy Konserwatorium Paryskim, w którym nauczał przez
			trzynaście lat.

			Po okresie prosperity, kilkanaście lat po premierze saksofonu, kariera Saxa podupadła. Doszło do tego, że
			Cesarz Napoleon III ratował go od bankructwa.

			W roku 1870 rząd rozwiązał klasę. Do końca życia żył w biedzie, na emeryturze ustanowionej przez rząd. Zmarł w
			siódmego lutego 1894 roku.
		</description>
		<extrainformation  kind="links">
			<link source="https://www.youtube.com/watch?v=TCg9jSSEOEc">Koncert saksofonowy</link>
		</extrainformation>
		<constructor>
			<name>Adolphe</name>
			<surname>Sax</surname>
			<birth>1814</birth>
			<death>1894</death>
			<description length="short">Antoine Joseph Sax, zwany Adolphe (1814-1894) – belgijski budowniczy instrumentów muzycznych, 
			konstruktor saksofonu.</description>
			<life>
				6 listopada 1814 roku urodziło się pierwsze z jedenaściorga dzieci Charlesa Josepha Saxa – 
				Antoine Joseph Sax zwany później Adolfem. Charles Sax, fabrykant, właściciel fabryki instrumentów 
				dętych, w rok po bitwie pod Waterloo mianowany został przez króla Zjednoczonych Niederlandów, Wilhelma 
				I głównym dostawcą instrumentów odradzającej się armii.

				W mieście Dinant było dużo drobnych warsztatów mechanicznych, wśród których europejską sławę zdobyły 
				warsztaty blacharskie, a szczególnie te, które pracowały na blachach z żółtej miedzi i mosiądzu. Adolf 
				Sax od wczesnych lat zaznajamiał się z kształtem, budową i technologią produkcji instrumentów dętych. 
				W wieku sześciu lat potrafił wytoczyć korpus klarnetu i roztrąb rogu. Od tego czasu pobierał 
				systematyczne lekcje gry na flecie w Konserwatorium Brukselskim i klarnecie u znanego dyrygenta 
				orkiestr wojskowych – L. Bendera.

				W roku 1829, mając piętnaście lat, posłał na wystawę do Paryża wykonane własnoręcznie dwa flety i 
				klarnet z kości słoniowej, które to instrumenty zostały uznane za świetne.

				W wieku 20. lat udoskonalił klarnet basowy, będący do tej pory instrumentem bardzo niestrojnym i 
				nierównym brzmieniowo. Od tego czasu zaczął borykać się ze złymi opiniami, przeciwnościami, a nawet 
				procesami ze strony konkurencji i muzyków, którzy powodowani zazdrością byli Saksowi niechętni. 
				Pierwsze spory dotyczyły unowocześnionego klarnetu basowego i dopiero konfrontacja instrumentów 
				starych i nowego spowodowała, że wynalazek został zaakceptowany.

				Wiosną 1841 roku Adolf Sax przeniósł się na jakiś czas do Paryża, gdzie obok uznania jako konstruktora i 
				wynalazcy spotkała go zawiść, napady krytyków i muzyków, oszczerstwa, procesy sądowe, a nawet kradzieże. 
				Z drugiej strony Sax miał wyjątkową zdolność robienia sobie nieprzyjaciół wynikającą z arogancji i 
				trudnego usposobienia.

				Po raz pierwszy o istniejącym już saksofonie napisał Hector Berlioz 12 czerwca 1842 roku w paryskim 
				Journal des débats. Saksofon (fr. Le Saxophon), nazywany od nazwiska swego wynalazcy, był instrumentem z 
				grupy dętych drewnianych. Miał dziewiętnaście klap, co czyniło go podobnym do instrumentu ophicleide. 
				Ustnik, w przeciwieństwie do dętych blaszanych, był podobny do ustnika klarnetu basowego. Pierwszym 
				saksofonem był saksofon barytonowy, dopiero później, z konieczności nadania większej ruchliwości, Adolf 
				Sax skonstruował alt, tenor i sopran. Skala pierwszego saksofonu była o siedem dźwięków większa niż 
				późniejsze modele, które Sax przebudował ze względu na gorsze możliwości brzmieniowe najwyższych 
				dźwięków prototypu. Wkrótce po premierze pierwszego saksofonu, Adolf Sax zademonstrował swoje 
				instrumenty w Konserwatorium Paryskim, gdzie słuchali go znani wówczas muzycy i kompozytorzy: 
				Auber (sławny kompozytor La Muette de Portici – opery wykonywanej w Brukseli 21 września 1830, 
				która stała się sygnałem dla rewolucji belgijskiej), Halévy, Habeneck, Monnais i inni, którzy chwalili 
				go za nowatorstwo i muzykalność.

				Po sukcesie prezentacji Sax otworzył warsztat w Paryżu przy ulicy Saint Georges 10, gdzie zabrał się
				energicznie do pracy, nader często jednak popadając w konflikty z zatrudnianymi rzemieślnikami. Na 
				siedemnastego i dwudziestego pierwszego czerwca przypadają daty pierwszych francuskich patentów 
				saksofonowych. Wiosną 1843 roku Sax rozpoczął produkcję instrumentów blaszanych z nowym mechanizmem 
				obrotowym zamiast tłokowego.
             </life>
		</constructor>
	</history>
	<types>
